#!/bin/bash
# scripts/install-addons.sh
# Install all custom add-ons (Homebrew + npm) for the Docker image.
# This script is called from the Dockerfile during build (as root).
#
# ⚠️  IMPORTANT: Any new packages added here MUST ALSO be documented in ADDONS.md
# See ADDONS.md for the source of truth on what should be installed.
# DO NOT edit this file without updating ADDONS.md simultaneously.

set -e

echo "Installing custom add-ons..."

# Ensure Homebrew is in PATH (it was installed as node user)
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"

# Verify brew is available
if ! command -v brew &> /dev/null; then
  echo "❌ Homebrew not found in PATH. Available PATH: $PATH"
  exit 1
fi

echo "✓ Homebrew found at: $(which brew)"

# ===== Homebrew Packages =====
echo ""
echo "Installing Homebrew packages..."

# Google Workspace CLI - DISABLED (tap too slow/unavailable)
# echo "→ Installing gog (Google Workspace CLI)..."
# if brew install steipete/tap/gogcli 2>&1; then
#   echo "✓ gog installed successfully"
# else
#   BREW_EXIT=$?
#   echo "⚠️  Warning: gog installation exited with code $BREW_EXIT (may already exist or tap unavailable)"
# fi

# GitHub CLI - DISABLED (Homebrew network issues in build)
# echo "→ Installing gh (GitHub CLI)..."
# if brew install gh 2>&1; then
#   echo "✓ gh installed successfully"
# else
#   BREW_EXIT=$?
#   echo "⚠️  Warning: gh installation exited with code $BREW_EXIT (may already exist)"
# fi

echo "✓ Homebrew packages processed."

# ===== NPM Global Packages =====
echo ""
echo "Installing npm global packages..."

# Verify npm is available
if ! command -v npm &> /dev/null; then
  echo "❌ npm not found in PATH"
  exit 1
fi

echo "✓ npm found at: $(which npm)"

# Coinbase CDP SDK
echo "→ Installing @coinbase/cdp-sdk..."
if npm install -g @coinbase/cdp-sdk --no-audit --no-fund 2>&1; then
  echo "✓ @coinbase/cdp-sdk installed successfully"
else
  echo "❌ @coinbase/cdp-sdk installation failed"
  exit 1
fi

echo "✓ npm global packages installed."

# ===== OpenClaw Extensions & Plugins =====
echo ""
echo "Installing OpenClaw extensions and plugins..."

# MoltGuard Security Plugin
echo "→ Installing MoltGuard (prompt injection detection plugin)..."
if mkdir -p ~/.openclaw/extensions/moltguard && \
   git clone --depth 1 https://github.com/openguardrails/moltguard.git /tmp/moltguard && \
   cp -r /tmp/moltguard/* ~/.openclaw/extensions/moltguard/ && \
   cd ~/.openclaw/extensions/moltguard && \
   npm install --omit=dev 2>&1 && \
   rm -rf /tmp/moltguard; then
  echo "✓ MoltGuard installed successfully to ~/.openclaw/extensions/moltguard"
else
  echo "❌ MoltGuard installation failed"
  exit 1
fi

echo "✓ OpenClaw extensions installed."

echo ""
echo "✅ All add-ons installed successfully."
