#!/bin/bash
# scripts/install-addons.sh
# Install all custom add-ons (Homebrew + npm) for the Docker image.
# This script is called from the Dockerfile during build (as root).
#
# ⚠️  IMPORTANT: Any new packages added here MUST ALSO be documented in ADDONS.md
# See ADDONS.md for the source of truth on what should be installed.
# DO NOT edit this file without updating ADDONS.md simultaneously.

set -e

echo "Installing custom add-ons..."

# ===== System Packages (APT) =====
echo ""
echo "Installing system packages via APT..."

apt-get update
apt-get install -y --no-install-recommends gh

echo "✓ System packages installed."

# ===== NPM Global Packages =====
echo ""
echo "Installing npm global packages..."

# Verify npm is available
if ! command -v npm &> /dev/null; then
  echo "❌ npm not found in PATH"
  exit 1
fi

echo "✓ npm found at: $(which npm)"

# Coinbase CDP SDK
echo "→ Installing @coinbase/cdp-sdk..."
if npm install -g @coinbase/cdp-sdk --no-audit --no-fund 2>&1; then
  echo "✓ @coinbase/cdp-sdk installed successfully"
else
  echo "❌ @coinbase/cdp-sdk installation failed"
  exit 1
fi

echo "✓ npm global packages installed."

# ===== OpenClaw Extensions & Plugins =====
echo ""
echo "Installing OpenClaw extensions and plugins..."

# MoltGuard Security Plugin
echo "→ Installing MoltGuard (prompt injection detection plugin)..."
if mkdir -p ~/.openclaw/extensions/moltguard && \
   git clone --depth 1 https://github.com/openguardrails/moltguard.git /tmp/moltguard && \
   cp -r /tmp/moltguard/* ~/.openclaw/extensions/moltguard/ && \
   cd ~/.openclaw/extensions/moltguard && \
   npm install --omit=dev 2>&1 && \
   rm -rf /tmp/moltguard; then
  echo "✓ MoltGuard installed successfully to ~/.openclaw/extensions/moltguard"
else
  echo "❌ MoltGuard installation failed"
  exit 1
fi

echo "✓ OpenClaw extensions installed."

# ===== OpenClaw Skills =====
echo ""
echo "Installing OpenClaw skills..."

# gog skill (Google Workspace CLI)
echo "→ Installing gog skill (Google Workspace integration)..."
if mkdir -p ~/.openclaw/workspace/skills && \
   cp -r /app/skills/gog ~/.openclaw/workspace/skills/gog; then
  echo "✓ gog skill installed successfully to ~/.openclaw/workspace/skills/gog"
else
  echo "⚠️  gog skill installation failed (non-blocking, may not exist in this build)"
fi

echo "✓ OpenClaw skills installed."

echo ""
echo "✅ All add-ons installed successfully."
